#!/usr/bin/env bash
# Generate kernel/whitelist.h from the built user binaries.
#
# The EDR whitelist is hash-based (mitigates DESIGN.md L1): at exec-time the
# kernel computes SHA-256 over the binary and matches it against this table.
# Renaming a whitelisted program no longer grants it whitelist privileges,
# and modifying a whitelisted binary revokes them.
#
# Usage: gen-whitelist.sh user/_init user/_sh ...
set -euo pipefail

progs=("$@")
[ ${#progs[@]} -gt 0 ] || { echo "usage: $0 <binary>..." >&2; exit 1; }

echo "// generated by scripts/gen-whitelist.sh - do not edit"
echo "#define WHITELIST_COUNT ${#progs[@]}"

i=0
for p in "${progs[@]}"; do
  name="$(basename "$p")"
  name="${name#_}"
  up="$(echo "$name" | tr 'a-z' 'A-Z')"
  echo "#define WL_IDX_${up} ${i}"
  i=$((i + 1))
done

echo ""
echo "static const unsigned char wl_hashes[WHITELIST_COUNT][32] = {"
hashes_concat=""
for p in "${progs[@]}"; do
  name="$(basename "$p")"
  name="${name#_}"
  h="$(sha256sum "$p" | cut -d' ' -f1)"
  hashes_concat+="${h}"
  bytes="$(echo "$h" | sed 's/../0x&, /g; s/, $//')"
  echo "  /* ${name} */"
  echo "  { ${bytes} },"
done
echo "};"

# P2: Signed whitelist – generate HMAC-like signature over hashes
# In production the secret would be a CI private key; for this
# educational project we use a fixed build secret to demonstrate the
# chain: build-time signing -> kernel verification at exec.
SECRET="xv6-edr-whitelist-signing-key-v1-2026-fresher-cv"
sig_input="${SECRET}${hashes_concat}"
sig="$(printf "%s" "$sig_input" | sha256sum | cut -d' ' -f1)"
sig_bytes="$(echo "$sig" | sed 's/../0x&, /g; s/, $//')"
echo ""
echo "// P2: whitelist signature (SHA-256 of SECRET + concatenated hashes)"
echo "static const unsigned char wl_signature[32] = { ${sig_bytes} };"
echo "static const char wl_secret[] = \"${SECRET}\";"
